# Project Servers
Host github
 HostName github.com
 User git
 ControlPersist no
 ControlPath none
 ControlMaster no
Host github.com
 HostName github.com
 User git
 ControlPersist no
 ControlPath none
 ControlMaster no
